-- Add all missing columns to services table
ALTER TABLE public.services 
ADD COLUMN IF NOT EXISTS features jsonb,
ADD COLUMN IF NOT EXISTS is_emergency boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS seo_keywords jsonb,
ADD COLUMN IF NOT EXISTS template_path text,
ADD COLUMN IF NOT EXISTS content_focus text,
ADD COLUMN IF NOT EXISTS target_word_count integer,
ADD COLUMN IF NOT EXISTS primary_cta_type text,
ADD COLUMN IF NOT EXISTS urgency_level text;

-- Now insert all 29 services with correct schema
INSERT INTO public.services (
  id, name, slug, category, short_description, full_description, features, 
  starting_price, is_emergency, is_active, seo_keywords, 
  template_path, content_focus, target_word_count, primary_cta_type, urgency_level
) VALUES
-- Authority Hub (6)
('7afd5ee1-0000-0000-0000-000000000001', 'Residential Roofing', 'residential-roofing', 'Authority Hub', 'Complete residential roofing solutions for New Orleans homes', 'Professional residential roofing services including new installation, complete replacement, and comprehensive repair solutions. We specialize in hurricane-resistant materials and Louisiana''s unique climate challenges, protecting your home with expert craftsmanship and premium materials.', '["Complete roof replacement","New construction roofing","Hurricane-resistant materials","25-50 year warranties","Energy efficient options","Free inspections"]'::jsonb, 850000, false, true, '["residential roofing","roof replacement","home roofing","roofing contractor","roof installation"]'::jsonb, 'authority-hub/residential-roofing.html', 'authority-building', 1200, 'form', 'low'),
('7afd5ee2-0000-0000-0000-000000000002', 'Commercial Roofing', 'commercial-roofing', 'Authority Hub', 'Professional commercial roofing solutions for businesses', 'Comprehensive commercial roofing services for office buildings, retail centers, warehouses, and industrial facilities. We handle flat roof systems, membrane installations, and large-scale roof replacements with minimal business disruption.', '["Flat roof systems","EPDM and TPO membranes","Metal commercial roofing","Roof maintenance programs","Emergency commercial repairs","Building code compliance"]'::jsonb, 1500000, false, true, '["commercial roofing","flat roof repair","business roofing","industrial roofing","commercial roof replacement"]'::jsonb, 'authority-hub/commercial-roofing.html', 'authority-building', 1200, 'form', 'low'),
('7afd5ee3-0000-0000-0000-000000000003', 'Emergency Roof Repair', 'emergency-roof-repair', 'Authority Hub', '24/7 emergency roof repair for active leaks and damage', 'Immediate emergency roof repair services for active leaks, storm damage, and urgent roofing issues. We provide immediate protection with emergency tarping and permanent repairs to prevent further damage to your property.', '["24/7 availability","Emergency tarping","Leak repairs","Storm damage response","Temporary protection","Immediate assessment"]'::jsonb, 75000, true, true, '["emergency roof repair","roof leak repair","24/7 roofing","urgent roof repair","emergency tarping"]'::jsonb, 'authority-hub/emergency-roof-repair.html', 'emergency-response', 800, 'emergency-phone', 'emergency'),
('7afd5ee4-0000-0000-0000-000000000004', 'Insurance Claims Assistance', 'insurance-claims-assistance', 'Authority Hub', 'Expert guidance through insurance claims for roof damage', 'Professional insurance claims assistance including damage documentation, adjuster meetings, claim advocacy, and settlement negotiation. We ensure you receive fair compensation for storm damage and help navigate the complex insurance process.', '["Claims documentation","Adjuster meetings","Damage assessments","Estimate preparation","Claim advocacy","Settlement negotiation"]'::jsonb, 50000, false, true, '["insurance claims","roof insurance","storm damage claims","insurance adjuster","claim assistance"]'::jsonb, 'authority-hub/insurance-claims-assistance.html', 'authority-building', 1400, 'form', 'medium'),
('7afd5ee5-0000-0000-0000-000000000005', 'Storm Damage Restoration', 'storm-damage-restoration', 'Authority Hub', '24/7 emergency storm damage repair and restoration services', 'Rapid response storm damage restoration including hail damage repair, wind damage restoration, emergency tarping, and complete storm recovery services. We work directly with insurance companies to expedite claims and restore your property quickly.', '["24/7 emergency response","Hail damage repair","Wind damage restoration","Emergency tarping","Structural assessments","Insurance coordination"]'::jsonb, 150000, true, true, '["storm damage repair","hail damage","wind damage","emergency roofing","hurricane damage","storm restoration"]'::jsonb, 'authority-hub/storm-damage-restoration.html', 'authority-building', 1300, 'emergency-phone', 'high'),
('7afd5ee6-0000-0000-0000-000000000006', 'General Contracting', 'general-contracting', 'Authority Hub', 'Complete property improvement and repair services', 'Full-service general contracting including siding installation, gutter systems, window replacement, exterior painting, and complete property renovations. We handle projects from small repairs to major home improvements.', '["Siding installation","Gutter systems","Window replacement","Exterior painting","Interior renovations","Property maintenance"]'::jsonb, 100000, false, true, '["general contractor","home improvement","siding installation","gutter repair","exterior renovation"]'::jsonb, 'authority-hub/general-contracting.html', 'authority-building', 1100, 'form', 'low'),
-- Emergency Services (3)
('7afd5ee7-0000-0000-0000-000000000007', 'Hail Damage Repair', 'hail-damage-repair', 'Emergency Services', 'Specialized hail damage assessment and repair services', 'Expert hail damage repair services including damage assessment, insurance documentation, and complete restoration for storm-damaged roofs. We respond quickly to protect your property from further damage.', '["Damage assessment","Insurance documentation","Complete restoration","Material matching","Quality guarantees","Fast response"]'::jsonb, 300000, true, true, '["hail damage repair","hail damage roof","storm damage","insurance claims","emergency repair"]'::jsonb, 'emergency-services/hail-damage-repair.html', 'emergency-response', 650, 'emergency-phone', 'high'),
('7afd5ee8-0000-0000-0000-000000000008', 'Leak Detection and Repair', 'leak-detection-repair', 'Emergency Services', 'Expert leak detection and emergency repair services', 'Advanced leak detection and repair services using thermal imaging and moisture meters to locate and fix roof leaks quickly. We provide immediate response to prevent water damage to your property.', '["Thermal imaging","Moisture detection","Emergency repairs","Preventive solutions","Warranty coverage","24/7 availability"]'::jsonb, 150000, true, true, '["roof leak detection","leak repair","emergency leak repair","water damage","roof repair"]'::jsonb, 'emergency-services/leak-detection-repair.html', 'emergency-response', 600, 'emergency-phone', 'emergency'),
('7afd5ee9-0000-0000-0000-000000000009', 'Wind Damage Restoration', 'wind-damage-restoration', 'Emergency Services', 'Complete wind damage restoration and emergency services', 'Rapid response wind damage restoration including emergency tarping, structural assessment, and complete rebuilding services. We work with your insurance company to restore your property quickly.', '["Emergency tarping","Structural assessment","Complete rebuilding","Insurance coordination","Temporary protection","24/7 response"]'::jsonb, 400000, true, true, '["wind damage repair","hurricane damage","storm restoration","emergency roofing","wind damage roof"]'::jsonb, 'emergency-services/wind-damage-restoration.html', 'emergency-response', 700, 'emergency-phone', 'emergency'),
-- Granular Services (20)
('7afd5ef1-0000-0000-0000-000000000011', 'Asphalt Shingle Roofing', 'asphalt-shingle-roofing', 'Granular Services', 'Professional asphalt shingle installation and repair services', 'Expert asphalt shingle roofing installation using hurricane-rated materials. Perfect for Louisiana''s climate with excellent durability and cost-effectiveness for New Orleans homes.', '["Architectural shingles","3-tab shingles","Hurricane-rated materials","25-30 year warranties","Energy efficient options","Professional installation"]'::jsonb, 650000, false, true, '["asphalt shingle roof","shingle roofing","architectural shingles","roof replacement","shingle repair"]'::jsonb, 'granular-services/asphalt-shingle-roofing.html', 'transactional', 800, 'phone', 'medium'),
('7afd5ef2-0000-0000-0000-000000000012', 'Metal Roofing', 'metal-roofing', 'Granular Services', 'Premium metal roofing installation and repair', 'Professional metal roofing installation including standing seam, metal shingles, and corrugated panels. Excellent for hurricane resistance and energy efficiency in Louisiana.', '["Standing seam metal","Metal shingles","Corrugated panels","50+ year lifespan","Hurricane resistance","Energy efficient"]'::jsonb, 1200000, false, true, '["metal roofing","standing seam roof","metal roof installation","aluminum roofing","steel roofing"]'::jsonb, 'granular-services/metal-roofing.html', 'transactional', 850, 'form', 'low'),
('7afd5ef3-0000-0000-0000-000000000013', 'Tile Roofing', 'tile-roofing', 'Granular Services', 'Beautiful and durable tile roofing installation and repair', 'Traditional and modern tile roofing systems including clay tiles, concrete tiles, and synthetic options. Perfect for New Orleans'' historic architecture and Mediterranean styles.', '["Clay tiles","Concrete tiles","Synthetic tiles","Historic restoration","Hurricane resistance","Lifetime durability"]'::jsonb, 1500000, false, true, '["tile roofing","clay tile roof","concrete tile roof","Spanish tile roofing","tile roof repair"]'::jsonb, 'granular-services/tile-roofing.html', 'transactional', 850, 'form', 'low'),
('7afd5ef4-0000-0000-0000-000000000014', 'Slate Roofing', 'slate-roofing', 'Granular Services', 'Premium slate roofing installation and historic restoration', 'Luxury slate roofing services including natural slate, synthetic slate, and historic slate roof restoration for New Orleans'' classic architecture.', '["Natural slate","Synthetic slate","Historic restoration","Custom installation","100+ year lifespan","Architectural matching"]'::jsonb, 2000000, false, true, '["slate roofing","slate roof repair","natural slate","synthetic slate","slate restoration"]'::jsonb, 'granular-services/slate-roofing.html', 'transactional', 900, 'form', 'low'),
('7afd5ef5-0000-0000-0000-000000000015', 'Flat Roof Systems', 'flat-roof-systems', 'Granular Services', 'Professional flat roof installation and maintenance services', 'Complete flat roofing solutions including EPDM, TPO, and modified bitumen systems for commercial and residential properties in New Orleans.', '["EPDM membrane","TPO roofing","Modified bitumen","Roof coatings","Drainage systems","Maintenance programs"]'::jsonb, 800000, false, true, '["flat roof repair","EPDM roofing","TPO roofing","modified bitumen","flat roof replacement"]'::jsonb, 'granular-services/flat-roof-systems.html', 'transactional', 800, 'form', 'medium'),
('7afd5ef6-0000-0000-0000-000000000016', 'Roof Coatings', 'roof-coatings', 'Granular Services', 'Protective roof coating application and maintenance services', 'Professional roof coating services including elastomeric, acrylic, and silicone coatings to extend roof life and improve energy efficiency in Louisiana''s climate.', '["Elastomeric coatings","Acrylic coatings","Silicone coatings","Energy efficiency","Leak prevention","Extended roof life"]'::jsonb, 400000, false, true, '["roof coating","elastomeric coating","silicone roof coating","roof restoration","cool roof coating"]'::jsonb, 'granular-services/roof-coatings.html', 'transactional', 700, 'phone', 'medium'),
('7afd5ef7-0000-0000-0000-000000000017', 'Gutter Installation', 'gutter-installation', 'Granular Services', 'Professional gutter installation and replacement services', 'Complete gutter system installation including seamless gutters, downspouts, and gutter guards to protect your New Orleans home from water damage.', '["Seamless gutters","Aluminum gutters","Gutter guards","Downspout installation","Proper drainage","Color matching"]'::jsonb, 150000, false, true, '["gutter installation","seamless gutters","gutter replacement","gutter repair","gutter guards"]'::jsonb, 'granular-services/gutter-installation.html', 'transactional', 750, 'phone', 'medium'),
('7afd5ef8-0000-0000-0000-000000000018', 'Siding Installation', 'siding-installation', 'Granular Services', 'Complete siding installation and replacement services', 'Professional siding installation including vinyl, fiber cement, and wood siding. We enhance your home''s protection and curb appeal with quality materials.', '["Vinyl siding","Fiber cement siding","Wood siding","Insulated siding","Color selection","Warranty coverage"]'::jsonb, 450000, false, true, '["siding installation","vinyl siding","fiber cement siding","siding replacement","siding repair"]'::jsonb, 'granular-services/siding-installation.html', 'transactional', 800, 'form', 'medium'),
('7afd5ef9-0000-0000-0000-000000000019', 'Window Installation', 'window-installation', 'Granular Services', 'Energy-efficient window installation and replacement', 'Professional window installation and replacement services featuring hurricane-rated and energy-efficient windows for New Orleans homes.', '["Hurricane windows","Energy efficient","Double pane glass","Custom sizing","Professional installation","Warranty coverage"]'::jsonb, 600000, false, true, '["window installation","window replacement","hurricane windows","energy efficient windows","window repair"]'::jsonb, 'granular-services/window-installation.html', 'transactional', 750, 'form', 'medium'),
('7afd5f01-0000-0000-0000-000000000020', 'Door Installation', 'door-installation', 'Granular Services', 'Exterior and interior door installation services', 'Complete door installation services including entry doors, storm doors, and French doors. We provide security and style for your New Orleans home.', '["Entry doors","Storm doors","French doors","Security features","Energy efficiency","Professional installation"]'::jsonb, 350000, false, true, '["door installation","door replacement","entry doors","storm doors","French doors"]'::jsonb, 'granular-services/door-installation.html', 'transactional', 700, 'phone', 'low'),
('7afd5f02-0000-0000-0000-000000000021', 'Skylight Installation', 'skylight-installation', 'Granular Services', 'Professional skylight installation and repair services', 'Expert skylight installation and repair services including traditional skylights, tubular skylights, and custom installations for natural lighting.', '["Traditional skylights","Tubular skylights","Leak-proof installation","Energy efficient glazing","Remote controls","Rain sensors"]'::jsonb, 120000, false, true, '["skylight installation","skylight repair","tubular skylights","skylight replacement","roof skylights"]'::jsonb, 'granular-services/skylight-installation.html', 'transactional', 700, 'phone', 'medium'),
('7afd5f03-0000-0000-0000-000000000022', 'Chimney Repair', 'chimney-repair', 'Granular Services', 'Complete chimney repair and restoration services', 'Professional chimney repair including crown repair, flashing installation, and masonry restoration for New Orleans area homes.', '["Crown repair","Flashing installation","Masonry restoration","Waterproofing","Structural repairs","Safety inspections"]'::jsonb, 250000, false, true, '["chimney repair","chimney flashing","chimney crown repair","chimney restoration","masonry repair"]'::jsonb, 'granular-services/chimney-repair.html', 'transactional', 750, 'phone', 'medium'),
('7afd5f04-0000-0000-0000-000000000023', 'Attic Ventilation', 'attic-ventilation', 'Granular Services', 'Attic ventilation installation and improvement services', 'Complete attic ventilation solutions including ridge vents, exhaust fans, and intake vents to improve energy efficiency and prevent moisture issues.', '["Ridge vents","Exhaust fans","Intake vents","Moisture control","Energy efficiency","Professional assessment"]'::jsonb, 80000, false, true, '["attic ventilation","ridge vents","exhaust fans","roof ventilation","attic fans"]'::jsonb, 'granular-services/attic-ventilation.html', 'transactional', 650, 'phone', 'low'),
('7afd5f05-0000-0000-0000-000000000024', 'Roof Inspection', 'roof-inspection', 'Granular Services', 'Comprehensive roof inspection and assessment services', 'Professional roof inspections including pre-purchase inspections, insurance inspections, and preventive maintenance assessments with detailed reporting.', '["Pre-purchase inspections","Insurance inspections","Maintenance assessments","Detailed reports","Photo documentation","Repair recommendations"]'::jsonb, 20000, false, true, '["roof inspection","roof assessment","roof evaluation","inspection services","roof condition report"]'::jsonb, 'granular-services/roof-inspection.html', 'transactional', 650, 'phone', 'low'),
('7afd5f06-0000-0000-0000-000000000025', 'Routine Maintenance', 'routine-maintenance', 'Granular Services', 'Regular roof maintenance and preventive care programs', 'Comprehensive roof maintenance programs including regular inspections, minor repairs, and preventive treatments to extend roof life.', '["Regular inspections","Minor repairs","Preventive treatments","Gutter cleaning","Debris removal","Maintenance schedules"]'::jsonb, 150000, false, true, '["roof maintenance","preventive maintenance","roof care","maintenance program","roof cleaning"]'::jsonb, 'granular-services/routine-maintenance.html', 'transactional', 700, 'form', 'low'),
('7afd5f07-0000-0000-0000-000000000026', 'Pressure Washing', 'pressure-washing', 'Granular Services', 'Professional pressure washing and exterior cleaning services', 'Complete pressure washing services for roofs, siding, driveways, and exterior surfaces to maintain your property''s appearance and value.', '["Roof cleaning","Siding cleaning","Driveway cleaning","Deck cleaning","Mold removal","Stain removal"]'::jsonb, 25000, false, true, '["pressure washing","roof cleaning","exterior cleaning","power washing","surface cleaning"]'::jsonb, 'granular-services/pressure-washing.html', 'transactional', 600, 'phone', 'low'),
('7afd5f08-0000-0000-0000-000000000027', 'Solar Roofing', 'solar-roofing', 'Granular Services', 'Solar panel integration and solar roofing system installation', 'Complete solar roofing solutions including solar panel installation, solar shingles, and roof-integrated solar systems with financing options.', '["Solar panel installation","Solar shingles","Roof integration","Energy audits","Financing options","Warranty coverage"]'::jsonb, 2500000, false, true, '["solar roofing","solar panels","solar shingles","solar installation","solar roof"]'::jsonb, 'granular-services/solar-roofing.html', 'transactional', 900, 'form', 'low'),
('7afd5f09-0000-0000-0000-000000000028', 'Green Roof Systems', 'green-roof-systems', 'Granular Services', 'Eco-friendly green roof and living roof installation', 'Sustainable green roofing solutions including extensive and intensive green roof systems for environmental benefits and energy efficiency.', '["Extensive green roofs","Intensive green roofs","Drainage systems","Plant selection","Waterproof membranes","Maintenance plans"]'::jsonb, 1800000, false, true, '["green roof","living roof","eco roof","sustainable roofing","vegetated roof"]'::jsonb, 'granular-services/green-roof-systems.html', 'transactional', 850, 'form', 'low'),
('7afd5f10-0000-0000-0000-000000000029', 'FORTIFIED Roof', 'fortified-roof', 'Granular Services', 'FORTIFIED designation roofing for superior storm protection', 'IBHS FORTIFIED roof installation for maximum hurricane and storm protection. Meet insurance requirements and protect your investment with certified installation.', '["FORTIFIED certification","Enhanced wind resistance","Insurance discounts","Sealed roof deck","Impact-rated materials","Professional certification"]'::jsonb, 1000000, false, true, '["FORTIFIED roof","FORTIFIED roofing","hurricane roof","storm resistant roof","IBHS FORTIFIED"]'::jsonb, 'granular-services/fortified-roof.html', 'transactional', 900, 'form', 'medium'),
('7afd5f11-0000-0000-0000-000000000030', 'Waterproofing Services', 'waterproofing-services', 'Granular Services', 'Complete waterproofing and moisture control services', 'Professional waterproofing services including basement waterproofing, foundation sealing, and moisture control for New Orleans area properties.', '["Basement waterproofing","Foundation sealing","Moisture barriers","Drainage systems","Vapor barriers","Lifetime warranties"]'::jsonb, 350000, false, true, '["waterproofing","basement waterproofing","foundation sealing","moisture control","water damage prevention"]'::jsonb, 'granular-services/waterproofing-services.html', 'transactional', 800, 'form', 'medium'),
('7afd5f12-0000-0000-0000-000000000031', 'Hurricane Preparation', 'hurricane-preparation', 'Granular Services', 'Hurricane preparation and storm-proofing services', 'Complete hurricane preparation services including roof reinforcement, impact-resistant installations, and emergency planning for Louisiana storm season.', '["Roof reinforcement","Impact-resistant materials","Emergency planning","Preventive measures","Storm shutters","Drainage improvements"]'::jsonb, 500000, false, true, '["hurricane preparation","storm preparation","hurricane proofing","storm protection","hurricane readiness"]'::jsonb, 'granular-services/hurricane-preparation.html', 'transactional', 800, 'form', 'medium');

-- Generate pages for all service × service_area combinations
INSERT INTO public.generated_pages (service_id, service_area_id, url_path, page_title, meta_description, status, needs_regeneration)
SELECT s.id, sa.id, '/' || sa.city_slug || '/' || s.slug, s.name || ' in ' || sa.city_name || ', ' || sa.state, s.short_description, true, true
FROM public.services s CROSS JOIN public.service_areas sa
WHERE s.is_active = true AND sa.status = true;